version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Dependabot - npm]"
    labels: [ "dependencies" ]
    milestone: 1
    groups:
      electron-forge:
        patterns:
          - "@electron-forge/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"