stages:
  - prepare
  - build_and_test

variables:
  NODE_IMAGE: gitlabregistry.exxeta.com/tech.io/know-how/skill-squad/rest-client/node:20

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

prepare:
  image: $NODE_IMAGE
  stage: prepare
  tags:
    - docker
    - performance
  script:
    - npm install
  only:
    - merge_requests
    - develop
  artifacts:
    paths:
      - node_modules/

test:
  image: $NODE_IMAGE
  stage: build_and_test
  tags:
    - docker
    - performance
  script:
    - npm test
  dependencies:
    - prepare
  only:
    - merge_requests
    - develop

build:
  image: $NODE_IMAGE
  stage: build_and_test
  tags:
    - docker
    - performance
  script:
    - npm run package
  dependencies:
    - prepare
  only:
    - merge_requests
    - develop
