title: Trufos Documentation
description: >-
  Trufos is a free, open source REST Client with offline support and no login required.

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme