name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install dependencies
        run: npm install

      - name: Save `node_modules` for later jobs
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Download node_modules from prepare job
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Run tests
        run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: gitlabregistry.exxeta.com/tech.io/know-how/skill-squad/rest-client/node:20
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Download node_modules from prepare job
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Build package
        run: npm run package