name: Validate Pull Request
run-name: Pull Request Validator

on:
  pull_request_target:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate the pull request
        uses: Namchee/conventional-pr@v0.15.4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          commit_pattern: '#[0-9]+ - .*'
          branch_pattern: '(feature|fix)\/[0-9]+(-[a-z]+)+'
          title_pattern: ''
